version: '3.8'

services:
  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      DYNAMODB_TABLE_NAME: ${DYNAMODB_TABLE_NAME}
    networks:
      - backend
    restart: always


  nginx:
    build:
      context: ./web
      dockerfile: Dockerfile.nginx
    networks:
      - backend
    ports:
      - "80:80"
    depends_on:
      - web

  test:
    build:
      context: ./web
      dockerfile: Dockerfile.test
    volumes:
      - ./web:/app
    environment:
      AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      DYNAMODB_TABLE_NAME: ${DYNAMODB_TABLE_NAME}
    networks:
      - backend



networks:
  backend:

volumes:
  jenkins_home:


